
#line 1 "Scanner.rl.cs"
// This file is AUTOGENERATED with RAGEL
// !!DO NOT EDIT!! Change the RL file and compile with Ragel
// See the ScannerGenerator directory.
// http://www.colm.net/open-source/ragel/
using System.Collections.Generic;
using Transition.Compiler.Tokens;

namespace Transition.Compiler
{
   /// <summary>
   /// Scanner performs lexical analysis on a string of characters and
   /// and emits a string of tokens for the Parser to analyze.
   /// </summary>
   public class Scanner
   {
      int _lineNumber = 0;
      bool _tokenUncommitted;
      int _tokenStart { get { return _token.StartIndex; } }
      Token _token;
      private List<Token> _tokens;

      // ragel properties
      private int eof;
      private int cs;
      private int p;

      private void StartToken(TokenType tokenType)
      {
        #if PARSER_LOGGING
        Log(string.Format("start {0}", tokenType));
        #endif
        _token = new Token {
            LineNumber = _lineNumber,
            StartIndex = p,
            TokenType = tokenType
        };
        _tokenUncommitted = true;
      }

      private void StartOperatorToken(TokenOperator tokenOperator)
      {
        #if PARSER_LOGGING
        Log(string.Format("start {0}", tokenOperator));
        #endif
        _token = new Token {
            LineNumber = _lineNumber,
            StartIndex = p,
            Operator = tokenOperator,
            TokenType = TokenType.Operator,
        };
        _tokenUncommitted = true;
      }

      #if PARSER_LOGGING
      private void Log(string msg) {
        Console.WriteLine(string.Format("{0} {1}", p, msg));
      }
      #endif

      private void EmitToken() {
        #if PARSER_LOGGING
        Log(string.Format("emit {0}", _token.TokenType));
        #endif
        _token.Length = p - _tokenStart;
        _tokens.Add(_token);
        _tokenUncommitted = false;
      }

      private void EmitNewLine() {
        _token.TokenType = TokenType.NewLine;
        #if PARSER_LOGGING
        Log(string.Format("emit {0}", _token.TokenType));
        #endif
        _tokens.Add(_token);
        _tokenUncommitted = false;
      }

      private void SetKeyword(TokenKeyword tokenKeyword) {
        _token.Keyword = tokenKeyword;
      }

      private void CommitLastToken() {
        if (_tokenUncommitted) {
          EmitToken();
        }
      }

      
#line 92 "tmp/Scanner.cs"
static readonly sbyte[] _Scanner_actions =  new sbyte [] {
	0, 1, 0, 1, 1, 1, 2, 1, 
	3, 1, 4, 1, 5, 1, 6, 1, 
	7, 1, 8, 1, 9, 1, 10, 1, 
	11, 1, 12, 2, 1, 0, 2, 1, 
	2, 2, 1, 3, 2, 1, 5, 2, 
	6, 1
};

static readonly short[] _Scanner_key_offsets =  new short [] {
	0, 0, 13, 15, 17, 21, 29, 37, 
	50, 62, 77, 79, 81, 88, 94, 110, 
	112, 127, 129, 131, 131, 132, 137, 142, 
	144, 146, 152, 157, 157, 159, 161, 161, 
	166, 168, 169, 170, 171, 177, 187, 202, 
	216, 229, 241, 246, 247, 252, 257, 259, 
	261, 267, 277, 292, 307, 321, 337, 339, 
	341, 341, 341, 343, 345, 345, 359, 365, 
	366, 367, 368, 369, 370, 371, 372, 373, 
	374, 375, 376, 377, 378, 379, 380, 380, 
	380, 393, 408, 424, 439, 454, 469
};

static readonly char[] _Scanner_trans_keys =  new char [] {
	'\u0020', '\u0022', '\u0023', '\u0027', '\u002d', '\u0040', '\u005f', '\u0009', 
	'\u000d', '\u0041', '\u005a', '\u0061', '\u007a', '\u0022', '\u005c', '\u0022', 
	'\u005c', '\u0020', '\u003a', '\u0009', '\u000d', '\u0020', '\u005f', '\u0009', 
	'\u000d', '\u0041', '\u005a', '\u0061', '\u007a', '\u0020', '\u005f', '\u0009', 
	'\u000d', '\u0041', '\u005a', '\u0061', '\u007a', '\u000a', '\u000d', '\u0020', 
	'\u0023', '\u005f', '\u0009', '\u000c', '\u0030', '\u0039', '\u0041', '\u005a', 
	'\u0061', '\u007a', '\u000a', '\u000d', '\u0020', '\u0022', '\u0027', '\u005f', 
	'\u0009', '\u000c', '\u0041', '\u005a', '\u0061', '\u007a', '\u000a', '\u000d', 
	'\u0020', '\u0022', '\u0023', '\u0027', '\u002d', '\u0040', '\u005f', '\u0009', 
	'\u000c', '\u0041', '\u005a', '\u0061', '\u007a', '\u0022', '\u005c', '\u0022', 
	'\u005c', '\u000a', '\u000d', '\u0020', '\u0023', '\u003a', '\u0009', '\u000c', 
	'\u000a', '\u000d', '\u0020', '\u003a', '\u0009', '\u000c', '\u000a', '\u000d', 
	'\u0020', '\u0022', '\u0023', '\u0027', '\u002d', '\u003a', '\u0040', '\u005f', 
	'\u0009', '\u000c', '\u0041', '\u005a', '\u0061', '\u007a', '\u000a', '\u000d', 
	'\u000a', '\u000d', '\u0020', '\u0022', '\u0023', '\u0027', '\u002d', '\u0040', 
	'\u005f', '\u0009', '\u000c', '\u0041', '\u005a', '\u0061', '\u007a', '\u0027', 
	'\u005c', '\u0027', '\u005c', '\u003e', '\u0020', '\u0022', '\u0027', '\u0009', 
	'\u000d', '\u0020', '\u0022', '\u0027', '\u0009', '\u000d', '\u0022', '\u005c', 
	'\u0022', '\u005c', '\u000a', '\u000d', '\u0020', '\u0023', '\u0009', '\u000c', 
	'\u000a', '\u000d', '\u0020', '\u0009', '\u000c', '\u0027', '\u005c', '\u0027', 
	'\u005c', '\u0065', '\u006d', '\u006f', '\u0072', '\u0073', '\u006e', '\u0078', 
	'\u0074', '\u0065', '\u0072', '\u000a', '\u000d', '\u0020', '\u0023', '\u0009', 
	'\u000c', '\u000a', '\u000d', '\u0020', '\u005f', '\u0009', '\u000c', '\u0041', 
	'\u005a', '\u0061', '\u007a', '\u000a', '\u000d', '\u0020', '\u0022', '\u0023', 
	'\u0027', '\u002d', '\u0040', '\u005f', '\u0009', '\u000c', '\u0041', '\u005a', 
	'\u0061', '\u007a', '\u000a', '\u000d', '\u0020', '\u0023', '\u002d', '\u005f', 
	'\u0009', '\u000c', '\u0030', '\u0039', '\u0041', '\u005a', '\u0061', '\u007a', 
	'\u000a', '\u000d', '\u0020', '\u0022', '\u0027', '\u002d', '\u005f', '\u0009', 
	'\u000c', '\u0041', '\u005a', '\u0061', '\u007a', '\u0020', '\u002d', '\u003a', 
	'\u005f', '\u0009', '\u000d', '\u0030', '\u0039', '\u0041', '\u005a', '\u0061', 
	'\u007a', '\u0020', '\u002d', '\u003a', '\u0009', '\u000d', '\u003e', '\u0020', 
	'\u0022', '\u0027', '\u0009', '\u000d', '\u0020', '\u0022', '\u0027', '\u0009', 
	'\u000d', '\u0022', '\u005c', '\u0022', '\u005c', '\u000a', '\u000d', '\u0020', 
	'\u0023', '\u0009', '\u000c', '\u000a', '\u000d', '\u0020', '\u005f', '\u0009', 
	'\u000c', '\u0041', '\u005a', '\u0061', '\u007a', '\u000a', '\u000d', '\u0020', 
	'\u0022', '\u0023', '\u0027', '\u002d', '\u0040', '\u005f', '\u0009', '\u000c', 
	'\u0041', '\u005a', '\u0061', '\u007a', '\u000a', '\u000d', '\u0020', '\u0023', 
	'\u002d', '\u003a', '\u005f', '\u0009', '\u000c', '\u0030', '\u0039', '\u0041', 
	'\u005a', '\u0061', '\u007a', '\u000a', '\u000d', '\u0020', '\u0022', '\u0027', 
	'\u002d', '\u003a', '\u005f', '\u0009', '\u000c', '\u0041', '\u005a', '\u0061', 
	'\u007a', '\u000a', '\u000d', '\u0020', '\u0022', '\u0023', '\u0027', '\u002d', 
	'\u003a', '\u0040', '\u005f', '\u0009', '\u000c', '\u0041', '\u005a', '\u0061', 
	'\u007a', '\u0027', '\u005c', '\u0027', '\u005c', '\u0027', '\u005c', '\u0027', 
	'\u005c', '\u000a', '\u000d', '\u0020', '\u0023', '\u002d', '\u005f', '\u0009', 
	'\u000c', '\u0030', '\u0039', '\u0041', '\u005a', '\u0061', '\u007a', '\u000a', 
	'\u000d', '\u0020', '\u002d', '\u0009', '\u000c', '\u0069', '\u0074', '\u0061', 
	'\u0063', '\u0068', '\u0069', '\u006e', '\u0065', '\u006e', '\u0075', '\u006e', 
	'\u0074', '\u0061', '\u0074', '\u0065', '\u0020', '\u0022', '\u0023', '\u0027', 
	'\u002d', '\u0040', '\u005f', '\u0009', '\u000d', '\u0041', '\u005a', '\u0061', 
	'\u007a', '\u000a', '\u000d', '\u0020', '\u0022', '\u0023', '\u0027', '\u002d', 
	'\u0040', '\u005f', '\u0009', '\u000c', '\u0041', '\u005a', '\u0061', '\u007a', 
	'\u000a', '\u000d', '\u0020', '\u0022', '\u0023', '\u0027', '\u002d', '\u003a', 
	'\u0040', '\u005f', '\u0009', '\u000c', '\u0041', '\u005a', '\u0061', '\u007a', 
	'\u000a', '\u000d', '\u0020', '\u0022', '\u0023', '\u0027', '\u002d', '\u0040', 
	'\u005f', '\u0009', '\u000c', '\u0041', '\u005a', '\u0061', '\u007a', '\u000a', 
	'\u000d', '\u0020', '\u0022', '\u0023', '\u0027', '\u002d', '\u0040', '\u005f', 
	'\u0009', '\u000c', '\u0041', '\u005a', '\u0061', '\u007a', '\u000a', '\u000d', 
	'\u0020', '\u0022', '\u0023', '\u0027', '\u002d', '\u0040', '\u005f', '\u0009', 
	'\u000c', '\u0041', '\u005a', '\u0061', '\u007a', '\u000a', '\u000d', '\u0020', 
	'\u0022', '\u0023', '\u0027', '\u002d', '\u003a', '\u0040', '\u005f', '\u0009', 
	'\u000c', '\u0041', '\u005a', '\u0061', '\u007a', (char) 0
};

static readonly sbyte[] _Scanner_single_lengths =  new sbyte [] {
	0, 7, 2, 2, 2, 2, 2, 5, 
	6, 9, 2, 2, 5, 4, 10, 2, 
	9, 2, 2, 0, 1, 3, 3, 2, 
	2, 4, 3, 0, 2, 2, 0, 5, 
	2, 1, 1, 1, 4, 4, 9, 6, 
	7, 4, 3, 1, 3, 3, 2, 2, 
	4, 4, 9, 7, 8, 10, 2, 2, 
	0, 0, 2, 2, 0, 6, 4, 1, 
	1, 1, 1, 1, 1, 1, 1, 1, 
	1, 1, 1, 1, 1, 1, 0, 0, 
	7, 9, 10, 9, 9, 9, 10
};

static readonly sbyte[] _Scanner_range_lengths =  new sbyte [] {
	0, 3, 0, 0, 1, 3, 3, 4, 
	3, 3, 0, 0, 1, 1, 3, 0, 
	3, 0, 0, 0, 0, 1, 1, 0, 
	0, 1, 1, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 1, 3, 3, 4, 
	3, 4, 1, 0, 1, 1, 0, 0, 
	1, 3, 3, 4, 3, 3, 0, 0, 
	0, 0, 0, 0, 0, 4, 1, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	3, 3, 3, 3, 3, 3, 3
};

static readonly short[] _Scanner_index_offsets =  new short [] {
	0, 0, 11, 14, 17, 21, 27, 33, 
	43, 53, 66, 69, 72, 79, 85, 99, 
	102, 115, 118, 121, 122, 124, 129, 134, 
	137, 140, 146, 151, 152, 155, 158, 159, 
	165, 168, 170, 172, 174, 180, 188, 201, 
	212, 223, 232, 237, 239, 244, 249, 252, 
	255, 261, 269, 282, 294, 306, 320, 323, 
	326, 327, 328, 331, 334, 335, 346, 352, 
	354, 356, 358, 360, 362, 364, 366, 368, 
	370, 372, 374, 376, 378, 380, 382, 383, 
	384, 395, 408, 422, 435, 448, 461
};

static readonly byte[] _Scanner_indicies =  new byte [] {
	0, 2, 3, 4, 5, 6, 7, 0, 
	7, 7, 1, 9, 10, 8, 12, 13, 
	11, 14, 15, 14, 1, 16, 17, 16, 
	17, 17, 1, 18, 7, 18, 7, 7, 
	1, 20, 21, 19, 22, 23, 19, 23, 
	23, 23, 1, 25, 26, 24, 27, 28, 
	29, 24, 29, 29, 1, 25, 31, 30, 
	32, 3, 33, 5, 6, 34, 30, 34, 
	34, 1, 36, 37, 35, 39, 40, 38, 
	42, 43, 41, 3, 15, 41, 1, 42, 
	43, 41, 15, 41, 1, 42, 45, 44, 
	2, 3, 4, 5, 15, 6, 7, 44, 
	7, 7, 1, 46, 47, 3, 46, 49, 
	48, 2, 3, 4, 5, 6, 7, 48, 
	7, 7, 1, 9, 51, 50, 12, 53, 
	52, 52, 54, 1, 55, 56, 57, 55, 
	1, 58, 27, 28, 58, 1, 60, 61, 
	59, 63, 64, 62, 46, 66, 65, 3, 
	65, 1, 46, 66, 65, 65, 1, 62, 
	60, 68, 67, 63, 70, 69, 69, 71, 
	72, 73, 74, 75, 1, 76, 77, 1, 
	78, 1, 79, 1, 80, 1, 82, 83, 
	81, 22, 81, 1, 85, 86, 84, 87, 
	84, 87, 87, 1, 85, 89, 88, 2, 
	3, 4, 5, 6, 90, 88, 90, 90, 
	1, 20, 92, 91, 22, 93, 94, 91, 
	94, 94, 94, 1, 25, 96, 95, 27, 
	28, 5, 29, 95, 29, 29, 1, 97, 
	98, 100, 99, 97, 99, 99, 99, 1, 
	101, 102, 103, 101, 1, 104, 1, 105, 
	106, 107, 105, 1, 108, 109, 110, 108, 
	1, 112, 113, 111, 115, 116, 114, 118, 
	119, 117, 3, 117, 1, 118, 119, 117, 
	29, 117, 29, 29, 1, 118, 121, 120, 
	2, 3, 4, 5, 6, 34, 120, 34, 
	34, 1, 123, 124, 122, 22, 98, 100, 
	125, 122, 125, 125, 125, 1, 127, 128, 
	126, 27, 28, 102, 103, 29, 126, 29, 
	29, 1, 127, 130, 129, 32, 3, 33, 
	102, 103, 6, 34, 129, 34, 34, 1, 
	36, 132, 131, 39, 134, 133, 133, 114, 
	112, 136, 135, 115, 138, 137, 137, 140, 
	141, 139, 22, 93, 142, 139, 142, 142, 
	142, 1, 46, 144, 143, 5, 143, 1, 
	145, 1, 146, 1, 147, 1, 148, 1, 
	149, 1, 150, 1, 151, 1, 152, 1, 
	153, 1, 154, 1, 155, 1, 156, 1, 
	157, 1, 158, 1, 159, 1, 38, 11, 
	0, 2, 3, 4, 5, 6, 7, 0, 
	7, 7, 1, 25, 31, 30, 32, 3, 
	33, 5, 6, 34, 30, 34, 34, 1, 
	42, 45, 44, 2, 3, 4, 5, 15, 
	6, 7, 44, 7, 7, 1, 46, 49, 
	48, 2, 3, 4, 5, 6, 7, 48, 
	7, 7, 1, 85, 89, 88, 2, 3, 
	4, 5, 6, 90, 88, 90, 90, 1, 
	118, 121, 120, 2, 3, 4, 5, 6, 
	34, 120, 34, 34, 1, 127, 130, 129, 
	32, 3, 33, 102, 103, 6, 34, 129, 
	34, 34, 1, 0
};

static readonly sbyte[] _Scanner_trans_targs =  new sbyte [] {
	1, 0, 2, 15, 17, 20, 31, 7, 
	3, 4, 79, 3, 4, 79, 4, 5, 
	6, 7, 6, 8, 81, 8, 15, 7, 
	8, 81, 8, 23, 28, 41, 9, 9, 
	10, 54, 51, 11, 12, 78, 11, 12, 
	78, 13, 82, 13, 14, 14, 83, 15, 
	16, 16, 18, 19, 18, 19, 21, 22, 
	23, 28, 22, 24, 25, 27, 24, 25, 
	27, 26, 26, 29, 30, 29, 30, 32, 
	65, 71, 72, 74, 33, 63, 34, 35, 
	36, 37, 84, 37, 37, 84, 37, 61, 
	38, 38, 39, 40, 40, 20, 39, 40, 
	40, 42, 43, 41, 44, 42, 43, 44, 
	44, 45, 46, 58, 45, 46, 58, 47, 
	48, 57, 47, 48, 57, 49, 85, 49, 
	50, 50, 52, 86, 52, 51, 52, 86, 
	52, 53, 53, 55, 56, 55, 56, 59, 
	60, 59, 60, 62, 83, 62, 61, 62, 
	62, 64, 36, 66, 67, 68, 69, 70, 
	36, 36, 73, 36, 75, 76, 77, 36
};

static readonly sbyte[] _Scanner_trans_actions =  new sbyte [] {
	0, 0, 0, 0, 0, 5, 9, 11, 
	13, 39, 13, 0, 3, 0, 0, 7, 
	3, 36, 0, 3, 27, 27, 3, 0, 
	0, 1, 1, 0, 0, 11, 0, 1, 
	0, 0, 11, 13, 39, 13, 0, 3, 
	0, 0, 1, 1, 0, 1, 1, 1, 
	0, 1, 13, 13, 0, 0, 0, 3, 
	3, 3, 0, 13, 39, 13, 0, 3, 
	0, 0, 1, 13, 13, 0, 0, 0, 
	0, 0, 0, 0, 0, 0, 0, 0, 
	21, 3, 27, 27, 0, 1, 1, 11, 
	0, 1, 11, 3, 27, 30, 0, 0, 
	1, 3, 30, 0, 33, 0, 5, 7, 
	0, 3, 3, 3, 0, 0, 0, 13, 
	39, 13, 0, 3, 0, 0, 1, 1, 
	0, 1, 3, 27, 27, 0, 0, 1, 
	1, 0, 1, 13, 13, 0, 0, 13, 
	13, 0, 0, 3, 27, 27, 0, 0, 
	1, 0, 23, 0, 0, 0, 0, 0, 
	15, 19, 0, 25, 0, 0, 0, 17
};

const int Scanner_start = 80;
const int Scanner_first_final = 80;
const int Scanner_error = 0;

const int Scanner_en_main = 80;


#line 92 "Scanner.rl.cs"


      ///<summary>
      /// This method will perform lexical analysis on the character sequence input
      //  and will return a sequence of tokens for the Parser to analyze.
      ///</summary>
      ///<returns>
      /// A sequence of tokens that the Parser can use to Analyze.
      ///</returns>
      public List<Token> Scan(char[] data, int len)
      {
         
#line 351 "tmp/Scanner.cs"
	{
	cs = Scanner_start;
	}

#line 104 "Scanner.rl.cs"
         if (_tokens == null) {
           _tokens = new List<Token>(128);
         }
         _tokens.Clear();
         _lineNumber = 1; // start at line 1 like most text editors
         p = 0;
         int pe = len;
         eof = len;
         
#line 366 "tmp/Scanner.cs"
	{
	sbyte _klen;
	short _trans;
	int _acts;
	int _nacts;
	short _keys;

	if ( p == pe )
		goto _test_eof;
	if ( cs == 0 )
		goto _out;
_resume:
	_keys = _Scanner_key_offsets[cs];
	_trans = (short)_Scanner_index_offsets[cs];

	_klen = _Scanner_single_lengths[cs];
	if ( _klen > 0 ) {
		short _lower = _keys;
		short _mid;
		short _upper = (short) (_keys + _klen - 1);
		while (true) {
			if ( _upper < _lower )
				break;

			_mid = (short) (_lower + ((_upper-_lower) >> 1));
			if ( data[p] < _Scanner_trans_keys[_mid] )
				_upper = (short) (_mid - 1);
			else if ( data[p] > _Scanner_trans_keys[_mid] )
				_lower = (short) (_mid + 1);
			else {
				_trans += (short) (_mid - _keys);
				goto _match;
			}
		}
		_keys += (short) _klen;
		_trans += (short) _klen;
	}

	_klen = _Scanner_range_lengths[cs];
	if ( _klen > 0 ) {
		short _lower = _keys;
		short _mid;
		short _upper = (short) (_keys + (_klen<<1) - 2);
		while (true) {
			if ( _upper < _lower )
				break;

			_mid = (short) (_lower + (((_upper-_lower) >> 1) & ~1));
			if ( data[p] < _Scanner_trans_keys[_mid] )
				_upper = (short) (_mid - 2);
			else if ( data[p] > _Scanner_trans_keys[_mid+1] )
				_lower = (short) (_mid + 2);
			else {
				_trans += (short)((_mid - _keys)>>1);
				goto _match;
			}
		}
		_trans += (short) _klen;
	}

_match:
	_trans = (short)_Scanner_indicies[_trans];
	cs = _Scanner_trans_targs[_trans];

	if ( _Scanner_trans_actions[_trans] == 0 )
		goto _again;

	_acts = _Scanner_trans_actions[_trans];
	_nacts = _Scanner_actions[_acts++];
	while ( _nacts-- > 0 )
	{
		switch ( _Scanner_actions[_acts++] )
		{
	case 0:
#line 4 "ScannerDef.rl"
	{ _lineNumber++; EmitNewLine(); }
	break;
	case 1:
#line 5 "ScannerDef.rl"
	{ EmitToken(); }
	break;
	case 2:
#line 6 "ScannerDef.rl"
	{ StartOperatorToken(TokenOperator.Transition); }
	break;
	case 3:
#line 7 "ScannerDef.rl"
	{ StartOperatorToken(TokenOperator.Assign); }
	break;
	case 4:
#line 8 "ScannerDef.rl"
	{ StartToken(TokenType.Keyword); }
	break;
	case 5:
#line 9 "ScannerDef.rl"
	{ StartToken(TokenType.Identifier); }
	break;
	case 6:
#line 10 "ScannerDef.rl"
	{ StartToken(TokenType.Value); }
	break;
	case 7:
#line 29 "ScannerDef.rl"
	{ SetKeyword(TokenKeyword.Machine); }
	break;
	case 8:
#line 30 "ScannerDef.rl"
	{ SetKeyword(TokenKeyword.State); }
	break;
	case 9:
#line 31 "ScannerDef.rl"
	{ SetKeyword(TokenKeyword.On); }
	break;
	case 10:
#line 32 "ScannerDef.rl"
	{ SetKeyword(TokenKeyword.Enter); }
	break;
	case 11:
#line 33 "ScannerDef.rl"
	{ SetKeyword(TokenKeyword.Exit); }
	break;
	case 12:
#line 34 "ScannerDef.rl"
	{ SetKeyword(TokenKeyword.Run); }
	break;
#line 492 "tmp/Scanner.cs"
		default: break;
		}
	}

_again:
	if ( cs == 0 )
		goto _out;
	if ( ++p != pe )
		goto _resume;
	_test_eof: {}
	_out: {}
	}

#line 113 "Scanner.rl.cs"
         CommitLastToken();
         return _tokens;
      }

      ///<summary>
      /// Call this method after Scan to know if the parser exited prematurely
      /// due to an error.
      ///</summary>
      ///<returns>
      /// A boolean indicating if the Scanner made it to the end of the input or not.
      ///</returns>
      public bool DidReachEndOfInput()
      {
         return (p >= eof);
      }
   }
}
