
#line 1 "Tokenizer.rl.cs"
// This file is AUTOGENERATED with RAGEL
// !!DO NOT EDIT!! Change the RL file and compile with Ragel
// http://www.colm.net/open-source/ragel/
using System;
using System.Collections.Generic;

namespace Statescript.Compiler
{

   public enum TokenOperator
   {
     Assign,
     Transition
   }
   
}
